name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret123!
          POSTGRES_DB: sticct_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d sticct_test" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      NODE_ENV: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: secret123!
      DB_DATABASE: sticct_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Run unit tests with coverage
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: 'backend/coverage/lcov.info'
          flags: backend
          fail_ci_if_error: true
          
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:cov
        env:
          CI: true
          CHROME_BIN: /usr/bin/google-chrome

      - name: Upload frontend coverage
        uses: codecov/codecov-action@v4
        with:
          files: 'frontend/coverage/sti-cct/lcov.info'
          flags: frontend
          fail_ci_if_error: true
          